# Generated by Django 3.0.6 on 2020-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='uploads',
        ),
    ]
